import {
  LayoutDashboard,
  Calendar,
  Users,
  BookOpen,
  FileText,
  Award,
  Lightbulb,
  CheckSquare,
  Clock,
  Mic,
  Mail,
  BookText,
  Settings,
  Target,
  CalendarDays,
  Rocket,
  Gamepad2,
  Store,
  Newspaper,
  Palette,
  Shapes,
  Bookmark as BookmarkIcon,
  Video,
} from 'lucide-react';

export const SIDEBAR_GROUPS = [
  { key: 'overview', label: '' },
  { key: 'teaching', label: 'Teaching' },
  { key: 'tutor', label: 'Tutor & Admin' },
  { key: 'projects', label: 'Projects' },
  { key: 'publishing', label: 'Publishing' },
  { key: 'productivity', label: 'Productivity' },
  { key: 'reference', label: 'Reference' },
] as const;

export const SIDEBAR_ITEMS = [
  { key: 'dashboard', icon: LayoutDashboard, label: 'Dashboard', group: 'overview' },
  { key: 'timetable', icon: Calendar, label: 'Calendar', group: 'teaching' },
  { key: 'teaching', icon: BookOpen, label: 'Teaching', group: 'teaching' },
  { key: 'lessons', icon: FileText, label: 'Lesson Records', group: 'teaching' },
  { key: 'hp-history', icon: Award, label: 'HP History', group: 'teaching' },
  { key: 'students', icon: Users, label: 'Students', group: 'tutor' },
  { key: 'meetings', icon: Mic, label: 'Meetings', group: 'tutor' },
  { key: 'events', icon: CalendarDays, label: 'School Events', group: 'tutor' },
  { key: 'email-digest', icon: Mail, label: 'Email Digest', group: 'tutor' },
  { key: 'projects', icon: Rocket, label: 'Projects', group: 'projects' },
  { key: 'video-hub', icon: Video, label: 'Video Hub', group: 'projects' },
  { key: 'kahoot-upload', icon: Gamepad2, label: 'Kahoot Hub', group: 'publishing' },
  { key: 'payhip-upload', icon: Store, label: 'Payhip Hub', group: 'publishing' },
  { key: 'paper-gen', icon: Newspaper, label: 'Paper Generator', group: 'publishing' },
  { key: 'cover-design', icon: Palette, label: 'Cover Designer', group: 'publishing' },
  { key: 'tikz-vault', icon: Shapes, label: 'TikzVault', group: 'publishing' },
  { key: 'tasks', icon: CheckSquare, label: 'GTD Tasks', group: 'productivity' },
  { key: 'worklogs', icon: Clock, label: 'Work Logs', group: 'productivity' },
  { key: 'ideas', icon: Lightbulb, label: 'Idea Pool', group: 'productivity' },
  { key: 'goals', icon: Target, label: 'Goals', group: 'productivity' },
  { key: 'bookmarks', icon: BookmarkIcon, label: 'Bookmarks', group: 'productivity' },
  { key: 'sop', icon: BookText, label: 'SOP Library', group: 'reference' },
  { key: 'settings', icon: Settings, label: 'Settings', group: 'reference' },
] as const;
