import {
  LayoutDashboard,
  Calendar,
  Users,
  BookOpen,
  FileText,
  Lightbulb,
  Clock,
  Mic,
  Settings,
  Target,
  CalendarDays,
  Terminal,
} from 'lucide-react';

export const SIDEBAR_ITEMS = [
  { key: 'dashboard', icon: LayoutDashboard, label: 'Dashboard' },
  { key: 'timetable', icon: Calendar, label: 'Calendar' },
  { key: 'students', icon: Users, label: 'Students' },
  { key: 'teaching', icon: BookOpen, label: 'Teaching' },
  { key: 'lessons', icon: FileText, label: 'Lesson Records' },
  { key: 'ideas', icon: Lightbulb, label: 'Idea Pool' },
  { key: 'worklogs', icon: Clock, label: 'Work Logs' },
  { key: 'goals', icon: Target, label: 'Goals' },
  { key: 'events', icon: CalendarDays, label: 'School Events' },
  { key: 'meetings', icon: Mic, label: 'Meetings' },
  { key: 'sop', icon: Settings, label: 'SOP Library' },
  { key: 'dev-console', icon: Terminal, label: 'Dev Console' },
  { key: 'settings', icon: Settings, label: 'Settings' },
] as const;
