export const SYLLABUS: Record<string, string[]> = {
  'Year 7': [
    'Unit 1: Multiplication of Fractions',
    'Unit 2: Position and Direction',
    'Unit 3: Division of Fraction',
    'Unit 4: Ratio',
    'Unit 5: Circle',
    'Unit 6: Percentage',
    'Unit 7: Pie Diagram',
    'Unit 8: Negative Number',
    'Unit 9: Percentage',
    'Unit 10: Cylinders and Cones',
    'Unit 11: Ratio and Proportion',
    'Unit 12: Linear Sequences',
    'Unit 13: Probability',
    'Unit 14: Constructions',
    'Unit 15: Review'
  ],
  'Year 8': [
    'Unit 1: Review of Numbers',
    'Unit 2: Rational Numbers, Factors and Primes',
    'Unit 3: Algebraic Formula',
    'Unit 4: Inequalties and Inequations',
    'Unit 5: Introduction to Pythagoras\' Theorem',
    'Unit 6: Intersecting Lines and Parallel Lines',
    'Unit 7: Further Algebra',
    'Unit 8: Co-ordinates and Plotting Linear Graphs',
    'Unit 9: Further Statistics'
  ],
  'Year 9': [
    'Unit 1: Working with Irrational Numbers',
    'Unit 2: Working with Expressions',
    'Unit 3: Algebraic Functions',
    'Unit 4: Mastery of Angles',
    'Unit 5: Practice with Constructions',
    'Unit 6: Congruence and Similarity',
    'Unit 7: Pythagoras Theorem',
    'Unit 8: 2D Shape',
    'Unit 9: Percentages',
    'Unit 10: Statistical Sampling',
    'Unit 11: Graphical Representation of Statistical Data',
    'Unit 12: Algebraic Fractions'
  ],
  'Year 10': [
    'Unit 1: Real Numbers',
    'Unit 2: Quadratic Equations',
    'Unit 3: Functions',
    'Unit 4: Further Trigonometry',
    'Unit 5: Circles',
    'Unit 6: Definitions and Theorems',
    'Unit 7: Transformations',
    'Unit 8: Probability',
    'Unit 9: 3D Geometry'
  ],
  'Year 11': [
    'Unit 1: Estimation & Bounds',
    'Unit 2: Set Notation & Venn Diagrams',
    'Unit 3: Simultaneous Equations',
    'Unit 4: Quadratic Sequences',
    'Unit 5: Differentiation',
    'Unit 6: Further Trigonometry',
    'Unit 7: Graphs of Trigonometric Functions',
    'Unit 8: Regions & Inequalities',
    'Unit 9: Vectors',
    'Unit 10: Functions'
  ],
  'Year 12': [
    'Pure 1 - 1. Algebraic Expressions',
    'Pure 1 - 2. Quadratics',
    'Pure 1 - 3. Equations and Inequalities',
    'Pure 1 - 4. Graphs and Transformations',
    'Pure 1 - 5. Straight Line Graphs',
    'Pure 1 - 6. Trigonometric Ratios',
    'Pure 1 - 7. Radians',
    'Pure 1 - 8. Differentiation',
    'Pure 1 - 9. Integration',
    'Pure 2 - 1. Algebraic Method',
    'Pure 2 - 2. Coordinate Geometry in the (x,y) plane',
    'Pure 2 - 3. Exponentials and Logarithms',
    'Pure 2 - 4. The Binomial Expansion',
    'Pure 2 - 5. Sequences and Series',
    'Pure 2 - 6. Trigonometric Identities and Equations',
    'Pure 2 - 7. Differentiation',
    'Pure 2 - 8. Integration'
  ]
};
